export default {
  title: 'NuxtLabs',
  description: 'Intuitive Web Development',
  url: 'https://nuxtlabs.com',
  template: 'docs',
  credits: true,
  socialImage: false,
  theme: {
    colors: {
      primary: {
        50: '#ededee',
        100: '#bfbfc5',
        200: '#94949e',
        300: '#7f7f8b',
        400: '#6b6b76',
        500: '#585860',
        600: '#44444b',
        700: '#313136',
        800: '#1d1d20',
        900: '#0a0a0b',
      },
      prism: {
        foreground: 'inherit',
        background: '#fbfbfb dark:#1e1e1e',
        class: '#9807af dark:#E879F9',
        builtin: '#9807af dark:#E879F9',
        function: '#9807af dark:#9807af',
        keyword: '#070707 dark:#429988',
        string: '#679c0d dark:#679c0d',
        number: '#679c0d dark:#679c0d',
        selector: '#679c0d dark:#679c0d',
        boolean: '#679c0d dark:#679c0d',
        property: '#070707 dark:#070707',
        punctuation: '#070707 dark:#070707',
        comment: '#758575 dark:#a0ada0',
        literal: '#429988 dark:#2f8a89',
        variable: 'inherit',
        constant: '#9807af dark:#9807af',
        deleted: '#a14f55 #a14f55',
        namespace: '#9807af dark:#9807af',
        decorator: '#9807af dark:#9807af',
        regex: '#679c0d dark:#BEF264',
        'json-property': '#070707 dark:#070707',
        'line-number': '#888888',
        'line-number-gutter': '#eeeeee',
        'line-highlight-background': '#444444',
        'selection-background': '#444444',
      },
    },
    shortcuts: {
      'd-logo': 'w-auto h-6 md:h-7 text-black',
      'd-body-bg': 'bg-white',
      'd-body-text-color': 'text-black',
      'd-heading-title': 'text-2xl xs:text-3xl sm:text-4xl lg:text-6xl',
      'd-primary-text-hover': 'text-gray-400',
      'd-prose-code-inline-bg': 'bg-dark-50',
      'd-prose-code-bg': 'bg-primary-50',
      'd-page-mobile-toc-bg': 'd-body-bg',
      'd-aside-header-bg': 'bg-white',
      'd-active-aside-navigation-item-bg': 'bg-primary-900',
      'd-active-aside-navigation-item-text': 'text-primary-500',
      'd-code-group-header-bg': 'bg-gray-200',
      'd-code-group-tab': 'bg-gray-300',
      'd-prose-code-filename-bg': 'bg-primary-100',
      'd-prose-code-filename-text': 'text-gray-600',
      'd-prose-thead-border': 'border-b border-gray-800',
      'd-prose-tr-border': 'border-b border-gray-900',
      'd-prose-blockquote-border': 'border-l-2 border-gray-800',
      'd-tertiary-text': 'text-cloud-dark',
      'd-prose-hr-border': 'border-t border-secondary-darker',
      'd-prose-ul-li-bullet': 'd-secondary-bg',
      'd-scrollbar': '',
      'd-prose-a-text': 'text-primary-300',
      // Container
      'd-max-w-container': 'max-w-7xl',
      'd-px-container': 'px-4 sm:px-8',
      'd-container': 'd-max-w-container mx-auto',
      'd-container-content': 'd-container d-px-container',
      // Illustration
      landscape: 'absolute m-auto w-full inset-x-0',
      'landscape-bottom': 'landscape bottom-0',
      'landscape-top': 'landscape bottom-full',
      'landscape-mobile': 'sm:hidden',
      'landscape-tablet': 'hidden sm:block lg:hidden',
      'landscape-desktop': 'hidden lg:block',
      'landscape-bottom-mobile': 'landscape-bottom landscape-mobile',
      'landscape-bottom-tablet': 'landscape-bottom landscape-tablet',
      'landscape-bottom-desktop': 'landscape-bottom landscape-desktop',
      'landscape-top-mobile': 'landscape-top landscape-mobile',
      'landscape-top-tablet': 'landscape-top landscape-tablet',
      'landscape-top-desktop': 'landscape-top landscape-desktop',
    },
  },
}
