import { defineThemeConfig } from 'docus'

export default defineThemeConfig({
  colors: {
    primary: {
      50: '#ededee',
      100: '#bfbfc5',
      200: '#94949e',
      300: '#7f7f8b',
      400: '#6b6b76',
      500: '#585860',
      600: '#44444b',
      700: '#313136',
      800: '#1d1d20',
      900: '#0a0a0b',
    },
  },
  shortcuts: {
    'd-logo': 'w-auto h-6 md:h-7 text-black',
    'd-body-bg': 'bg-white',
    'd-body-text-color': 'text-black',
    'd-heading-title': 'text-2xl xs:text-3xl sm:text-4xl lg:text-6xl',
    'd-primary-text-hover': 'text-gray-400',
    'd-prose-code-inline-bg': 'bg-gray-200',
    'd-prose-code-bg': 'bg-gray-50',
    'd-page-mobile-toc-bg': 'd-body-bg',
    'd-aside-header-bg': 'bg-white',
    'd-active-aside-navigation-item-bg': 'bg-primary-900',
    'd-active-aside-navigation-item-text': 'text-primary-500',
    'd-code-group-header-bg': 'bg-gray-200',
    'd-code-group-tab': 'bg-gray-300',
    'd-prose-code-filename-bg': 'bg-gray-300',
    'd-prose-code-filename-text': 'text-gray-600',
    'd-prose-thead-border': 'border-b border-gray-800',
    'd-prose-tr-border': 'border-b border-gray-900',
    'd-prose-blockquote-border': 'border-l-2 border-gray-800',
    'd-tertiary-text': 'text-cloud-dark',
    'd-prose-hr-border': 'border-t border-secondary-darker',
    'd-prose-ul-li-bullet': 'd-secondary-bg',
    'd-scrollbar': '',
    // Container
    'd-max-w-container': 'max-w-7xl',
    'd-px-container': 'px-4 sm:px-8',
    'd-container': 'd-max-w-container mx-auto',
    'd-container-content': 'd-container d-px-container',
    // Illustration
    landscape: 'absolute m-auto w-full',
    'landscape-bottom': 'landscape bottom-0',
    'landscape-top': 'landscape bottom-full',
    'landscape-mobile': 'sm:hidden',
    'landscape-tablet': 'hidden sm:block lg:hidden',
    'landscape-desktop': 'hidden lg:block',
    'landscape-bottom-mobile': 'landscape-bottom landscape-mobile',
    'landscape-bottom-tablet': 'landscape-bottom landscape-tablet',
    'landscape-bottom-desktop': 'landscape-bottom landscape-desktop',
    'landscape-top-mobile': 'landscape-top landscape-mobile',
    'landscape-top-tablet': 'landscape-top landscape-tablet',
    'landscape-top-desktop': 'landscape-top landscape-desktop',
  },
})
